chore: enforce test coverage (#159)
* chore: enforce test coverage

Signed-off-by: Travis Truman <trumant@gmail.com>

* fix: Makefile coverage read before coverage execution

* chore(ci): raise test coverage requirement to 26%

This level reflects the current coverage, up from 24% when this change was originally proposed.

---------

Signed-off-by: Travis Truman <trumant@gmail.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -11,7 +11,7 @@ permissions:
   pull-requests: read
 
 jobs:
-  lint:
+  build:
     name: build
     runs-on: ubuntu-latest
     steps:
@@ -25,3 +25,18 @@ jobs:
         run: make build
       - name: test
         run: make test-cov
+      - name: test coverage check
+        env:
+          TESTCOVERAGE_THRESHOLD: 26
+        run: |
+          echo "Quality Gate: checking test coverage is above threshold ..."
+          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
+              echo "OK"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Failed"
+              exit 1
+          fi
